name: SMPStat
version: '1.0-ALPHA'
main: net.smpstat.SmpStat
api-version: '1.21'
commands:
  setsecret:
    description: Sets the Server Secret
    usage: /setsecret <value>
    permission: smpstat.admin